### PR TITLE
Remove github actions

### PR DESCRIPTION
**Pull request by orkunkl**
No need for this, there is Circle CI builds

### CODE REVIEW

**Comment by webmaster128** [comment]
Why is this removed? Isn't it nice for users to be able to decide between the two? Not everyone enjoys the free version of circleci or is paying for the service as Confio does.

**Comment by orkunkl** [comment]
We came across this with @ethanfrey during the internal smart contract workshop, and I thought sticking to circle ci would be simpler, but yeah you are right why not provide both

**Comment by webmaster128** [comment]
In the beginning there were a good amount of external people pushing for the GitHub Actions config. I don't have super strong opinions here but we should keep in mind this is not Confio only and Confio gets 80x parallelization and all the fancyness because we pay for CircleCI.

**Comment by webmaster128** [comment]
It would be cool to try this:

> Sometimes templates need to make decisions. For example one might want to conditionally include some code or not. Another use case might be that the user of a template should be able to choose out of provided options in an interactive way. Also it might be helpful to offer a reasonable default value that the user just simply can use.

https://github.com/cargo-generate/cargo-generate#template-defined-placeholders

which could be used to ask the user which one they want when generating.

**Comment by ethanfrey** [comment]
I would leave for now, but fix to use Rust 1.51.0
Many other teams did ask for this.

I like the template idea, but that is another story

**Comment by orkunkl** [comment]
Closing the PR now, will create new one to update to 1.51.0

**Pull request closed without merging**
